/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExamRecord = IDL.Record({
  'marks' : IDL.Float64,
  'studentId' : IDL.Text,
  'subject' : IDL.Text,
  'systemId' : IDL.Text,
  'grade' : IDL.Text,
  'timestamp' : IDL.Int,
  'position' : IDL.Nat,
  'remarks' : IDL.Text,
});
export const FinancialType = IDL.Variant({
  'revenue' : IDL.Null,
  'expense' : IDL.Null,
});
export const FinancialRecord = IDL.Record({
  'description' : IDL.Text,
  'recordType' : FinancialType,
  'systemId' : IDL.Text,
  'timestamp' : IDL.Int,
  'amount' : IDL.Float64,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const StaffStatus = IDL.Variant({
  'active' : IDL.Null,
  'transferred' : IDL.Null,
  'dismissed' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Staff = IDL.Record({
  'status' : StaffStatus,
  'name' : IDL.Text,
  'systemId' : IDL.Text,
  'photo' : IDL.Opt(ExternalBlob),
  'position' : IDL.Text,
});
export const AdmissionStatus = IDL.Variant({
  'active' : IDL.Null,
  'transferred' : IDL.Null,
  'dismissed' : IDL.Null,
  'promoted' : IDL.Null,
});
export const Student = IDL.Record({
  'status' : AdmissionStatus,
  'parentPhone' : IDL.Text,
  'systemId' : IDL.Text,
  'photo' : IDL.Opt(ExternalBlob),
  'className' : IDL.Text,
  'lastName' : IDL.Text,
  'parentName' : IDL.Text,
  'firstName' : IDL.Text,
});
export const AppRole = IDL.Variant({
  'accountant' : IDL.Null,
  'examsCoordinator' : IDL.Null,
  'headmaster' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'active' : IDL.Bool,
  'appRole' : AppRole,
  'role' : UserRole,
  'lastUpdated' : IDL.Int,
  'fullName' : IDL.Text,
  'systemId' : IDL.Text,
  'photo' : IDL.Opt(ExternalBlob),
});
export const AuditLog = IDL.Record({
  'action' : IDL.Text,
  'user' : IDL.Principal,
  'timestamp' : IDL.Int,
  'details' : IDL.Text,
});
export const SMSLog = IDL.Record({
  'deliveryStatus' : IDL.Text,
  'systemId' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'receiver' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addExamRecord' : IDL.Func([ExamRecord], [], []),
  'addFinancialRecord' : IDL.Func([FinancialRecord], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createStaff' : IDL.Func([Staff], [], []),
  'createStudent' : IDL.Func([Student], [], []),
  'createUser' : IDL.Func([IDL.Principal, UserProfile], [], []),
  'deleteExamRecord' : IDL.Func([IDL.Text], [], []),
  'deleteFinancialRecord' : IDL.Func([IDL.Text], [], []),
  'deleteStaff' : IDL.Func([IDL.Text], [], []),
  'deleteStudent' : IDL.Func([IDL.Text], [], []),
  'disableUser' : IDL.Func([IDL.Principal], [], []),
  'dismissStudent' : IDL.Func([IDL.Text], [], []),
  'exportAllData' : IDL.Func([], [IDL.Text], ['query']),
  'getAllExamRecords' : IDL.Func([], [IDL.Vec(ExamRecord)], ['query']),
  'getAllFinancialRecords' : IDL.Func(
      [],
      [IDL.Vec(FinancialRecord)],
      ['query'],
    ),
  'getAllStaff' : IDL.Func([], [IDL.Vec(Staff)], ['query']),
  'getAllStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
  'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getAuditLogs' : IDL.Func([], [IDL.Vec(AuditLog)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getExamRecord' : IDL.Func([IDL.Text], [IDL.Opt(ExamRecord)], ['query']),
  'getFinancialRecord' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(FinancialRecord)],
      ['query'],
    ),
  'getSMSLogs' : IDL.Func([], [IDL.Vec(SMSLog)], ['query']),
  'getStaff' : IDL.Func([IDL.Text], [IDL.Opt(Staff)], ['query']),
  'getStudent' : IDL.Func([IDL.Text], [IDL.Opt(Student)], ['query']),
  'getStudentExamRecords' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ExamRecord)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'importData' : IDL.Func([IDL.Text], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'logSMS' : IDL.Func([SMSLog], [], []),
  'resetUserPassword' : IDL.Func([IDL.Principal], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'transferStudent' : IDL.Func([IDL.Text], [], []),
  'updateExamRecord' : IDL.Func([ExamRecord], [], []),
  'updateFinancialRecord' : IDL.Func([FinancialRecord], [], []),
  'updateStaff' : IDL.Func([Staff], [], []),
  'updateStudent' : IDL.Func([Student], [], []),
  'updateUser' : IDL.Func([IDL.Principal, UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExamRecord = IDL.Record({
    'marks' : IDL.Float64,
    'studentId' : IDL.Text,
    'subject' : IDL.Text,
    'systemId' : IDL.Text,
    'grade' : IDL.Text,
    'timestamp' : IDL.Int,
    'position' : IDL.Nat,
    'remarks' : IDL.Text,
  });
  const FinancialType = IDL.Variant({
    'revenue' : IDL.Null,
    'expense' : IDL.Null,
  });
  const FinancialRecord = IDL.Record({
    'description' : IDL.Text,
    'recordType' : FinancialType,
    'systemId' : IDL.Text,
    'timestamp' : IDL.Int,
    'amount' : IDL.Float64,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const StaffStatus = IDL.Variant({
    'active' : IDL.Null,
    'transferred' : IDL.Null,
    'dismissed' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Staff = IDL.Record({
    'status' : StaffStatus,
    'name' : IDL.Text,
    'systemId' : IDL.Text,
    'photo' : IDL.Opt(ExternalBlob),
    'position' : IDL.Text,
  });
  const AdmissionStatus = IDL.Variant({
    'active' : IDL.Null,
    'transferred' : IDL.Null,
    'dismissed' : IDL.Null,
    'promoted' : IDL.Null,
  });
  const Student = IDL.Record({
    'status' : AdmissionStatus,
    'parentPhone' : IDL.Text,
    'systemId' : IDL.Text,
    'photo' : IDL.Opt(ExternalBlob),
    'className' : IDL.Text,
    'lastName' : IDL.Text,
    'parentName' : IDL.Text,
    'firstName' : IDL.Text,
  });
  const AppRole = IDL.Variant({
    'accountant' : IDL.Null,
    'examsCoordinator' : IDL.Null,
    'headmaster' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'active' : IDL.Bool,
    'appRole' : AppRole,
    'role' : UserRole,
    'lastUpdated' : IDL.Int,
    'fullName' : IDL.Text,
    'systemId' : IDL.Text,
    'photo' : IDL.Opt(ExternalBlob),
  });
  const AuditLog = IDL.Record({
    'action' : IDL.Text,
    'user' : IDL.Principal,
    'timestamp' : IDL.Int,
    'details' : IDL.Text,
  });
  const SMSLog = IDL.Record({
    'deliveryStatus' : IDL.Text,
    'systemId' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'receiver' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addExamRecord' : IDL.Func([ExamRecord], [], []),
    'addFinancialRecord' : IDL.Func([FinancialRecord], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createStaff' : IDL.Func([Staff], [], []),
    'createStudent' : IDL.Func([Student], [], []),
    'createUser' : IDL.Func([IDL.Principal, UserProfile], [], []),
    'deleteExamRecord' : IDL.Func([IDL.Text], [], []),
    'deleteFinancialRecord' : IDL.Func([IDL.Text], [], []),
    'deleteStaff' : IDL.Func([IDL.Text], [], []),
    'deleteStudent' : IDL.Func([IDL.Text], [], []),
    'disableUser' : IDL.Func([IDL.Principal], [], []),
    'dismissStudent' : IDL.Func([IDL.Text], [], []),
    'exportAllData' : IDL.Func([], [IDL.Text], ['query']),
    'getAllExamRecords' : IDL.Func([], [IDL.Vec(ExamRecord)], ['query']),
    'getAllFinancialRecords' : IDL.Func(
        [],
        [IDL.Vec(FinancialRecord)],
        ['query'],
      ),
    'getAllStaff' : IDL.Func([], [IDL.Vec(Staff)], ['query']),
    'getAllStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
    'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getAuditLogs' : IDL.Func([], [IDL.Vec(AuditLog)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getExamRecord' : IDL.Func([IDL.Text], [IDL.Opt(ExamRecord)], ['query']),
    'getFinancialRecord' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(FinancialRecord)],
        ['query'],
      ),
    'getSMSLogs' : IDL.Func([], [IDL.Vec(SMSLog)], ['query']),
    'getStaff' : IDL.Func([IDL.Text], [IDL.Opt(Staff)], ['query']),
    'getStudent' : IDL.Func([IDL.Text], [IDL.Opt(Student)], ['query']),
    'getStudentExamRecords' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ExamRecord)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'importData' : IDL.Func([IDL.Text], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'logSMS' : IDL.Func([SMSLog], [], []),
    'resetUserPassword' : IDL.Func([IDL.Principal], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'transferStudent' : IDL.Func([IDL.Text], [], []),
    'updateExamRecord' : IDL.Func([ExamRecord], [], []),
    'updateFinancialRecord' : IDL.Func([FinancialRecord], [], []),
    'updateStaff' : IDL.Func([Staff], [], []),
    'updateStudent' : IDL.Func([Student], [], []),
    'updateUser' : IDL.Func([IDL.Principal, UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };