/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AdmissionStatus = { 'active' : null } |
  { 'transferred' : null } |
  { 'dismissed' : null } |
  { 'promoted' : null };
export type AppRole = { 'accountant' : null } |
  { 'examsCoordinator' : null } |
  { 'headmaster' : null };
export interface AuditLog {
  'action' : string,
  'user' : Principal,
  'timestamp' : bigint,
  'details' : string,
}
export interface ExamRecord {
  'marks' : number,
  'studentId' : string,
  'subject' : string,
  'systemId' : string,
  'grade' : string,
  'timestamp' : bigint,
  'position' : bigint,
  'remarks' : string,
}
export type ExternalBlob = Uint8Array;
export interface FinancialRecord {
  'description' : string,
  'recordType' : FinancialType,
  'systemId' : string,
  'timestamp' : bigint,
  'amount' : number,
}
export type FinancialType = { 'revenue' : null } |
  { 'expense' : null };
export interface SMSLog {
  'deliveryStatus' : string,
  'systemId' : string,
  'message' : string,
  'timestamp' : bigint,
  'receiver' : string,
}
export interface Staff {
  'status' : StaffStatus,
  'name' : string,
  'systemId' : string,
  'photo' : [] | [ExternalBlob],
  'position' : string,
}
export type StaffStatus = { 'active' : null } |
  { 'transferred' : null } |
  { 'dismissed' : null };
export interface Student {
  'status' : AdmissionStatus,
  'parentPhone' : string,
  'systemId' : string,
  'photo' : [] | [ExternalBlob],
  'className' : string,
  'lastName' : string,
  'parentName' : string,
  'firstName' : string,
}
export interface UserProfile {
  'active' : boolean,
  'appRole' : AppRole,
  'role' : UserRole,
  'lastUpdated' : bigint,
  'fullName' : string,
  'systemId' : string,
  'photo' : [] | [ExternalBlob],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addExamRecord' : ActorMethod<[ExamRecord], undefined>,
  'addFinancialRecord' : ActorMethod<[FinancialRecord], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createStaff' : ActorMethod<[Staff], undefined>,
  'createStudent' : ActorMethod<[Student], undefined>,
  'createUser' : ActorMethod<[Principal, UserProfile], undefined>,
  'deleteExamRecord' : ActorMethod<[string], undefined>,
  'deleteFinancialRecord' : ActorMethod<[string], undefined>,
  'deleteStaff' : ActorMethod<[string], undefined>,
  'deleteStudent' : ActorMethod<[string], undefined>,
  'disableUser' : ActorMethod<[Principal], undefined>,
  'dismissStudent' : ActorMethod<[string], undefined>,
  'exportAllData' : ActorMethod<[], string>,
  'getAllExamRecords' : ActorMethod<[], Array<ExamRecord>>,
  'getAllFinancialRecords' : ActorMethod<[], Array<FinancialRecord>>,
  'getAllStaff' : ActorMethod<[], Array<Staff>>,
  'getAllStudents' : ActorMethod<[], Array<Student>>,
  'getAllUsers' : ActorMethod<[], Array<UserProfile>>,
  'getAuditLogs' : ActorMethod<[], Array<AuditLog>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getExamRecord' : ActorMethod<[string], [] | [ExamRecord]>,
  'getFinancialRecord' : ActorMethod<[string], [] | [FinancialRecord]>,
  'getSMSLogs' : ActorMethod<[], Array<SMSLog>>,
  'getStaff' : ActorMethod<[string], [] | [Staff]>,
  'getStudent' : ActorMethod<[string], [] | [Student]>,
  'getStudentExamRecords' : ActorMethod<[string], Array<ExamRecord>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'importData' : ActorMethod<[string], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'logSMS' : ActorMethod<[SMSLog], undefined>,
  'resetUserPassword' : ActorMethod<[Principal], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'transferStudent' : ActorMethod<[string], undefined>,
  'updateExamRecord' : ActorMethod<[ExamRecord], undefined>,
  'updateFinancialRecord' : ActorMethod<[FinancialRecord], undefined>,
  'updateStaff' : ActorMethod<[Staff], undefined>,
  'updateStudent' : ActorMethod<[Student], undefined>,
  'updateUser' : ActorMethod<[Principal, UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];