/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface UserProfile {
    active: boolean;
    appRole: AppRole;
    role: UserRole;
    lastUpdated: bigint;
    fullName: string;
    systemId: string;
    photo?: ExternalBlob;
}
export interface Student {
    status: AdmissionStatus;
    parentPhone: string;
    systemId: string;
    photo?: ExternalBlob;
    className: string;
    lastName: string;
    parentName: string;
    firstName: string;
}
export interface AuditLog {
    action: string;
    user: Principal;
    timestamp: bigint;
    details: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface FinancialRecord {
    description: string;
    recordType: FinancialType;
    systemId: string;
    timestamp: bigint;
    amount: number;
}
export interface SMSLog {
    deliveryStatus: string;
    systemId: string;
    message: string;
    timestamp: bigint;
    receiver: string;
}
export interface Staff {
    status: StaffStatus;
    name: string;
    systemId: string;
    photo?: ExternalBlob;
    position: string;
}
export interface ExamRecord {
    marks: number;
    studentId: string;
    subject: string;
    systemId: string;
    grade: string;
    timestamp: bigint;
    position: bigint;
    remarks: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum AdmissionStatus {
    active = "active",
    transferred = "transferred",
    dismissed = "dismissed",
    promoted = "promoted"
}
export enum AppRole {
    accountant = "accountant",
    examsCoordinator = "examsCoordinator",
    headmaster = "headmaster"
}
export enum FinancialType {
    revenue = "revenue",
    expense = "expense"
}
export enum StaffStatus {
    active = "active",
    transferred = "transferred",
    dismissed = "dismissed"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addExamRecord(record: ExamRecord): Promise<void>;
    addFinancialRecord(record: FinancialRecord): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createStaff(staff: Staff): Promise<void>;
    createStudent(student: Student): Promise<void>;
    createUser(userId: Principal, profile: UserProfile): Promise<void>;
    deleteExamRecord(id: string): Promise<void>;
    deleteFinancialRecord(id: string): Promise<void>;
    deleteStaff(id: string): Promise<void>;
    deleteStudent(id: string): Promise<void>;
    disableUser(userId: Principal): Promise<void>;
    dismissStudent(id: string): Promise<void>;
    exportAllData(): Promise<string>;
    getAllExamRecords(): Promise<Array<ExamRecord>>;
    getAllFinancialRecords(): Promise<Array<FinancialRecord>>;
    getAllStaff(): Promise<Array<Staff>>;
    getAllStudents(): Promise<Array<Student>>;
    getAllUsers(): Promise<Array<UserProfile>>;
    getAuditLogs(): Promise<Array<AuditLog>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getExamRecord(id: string): Promise<ExamRecord | null>;
    getFinancialRecord(id: string): Promise<FinancialRecord | null>;
    getSMSLogs(): Promise<Array<SMSLog>>;
    getStaff(id: string): Promise<Staff | null>;
    getStudent(id: string): Promise<Student | null>;
    getStudentExamRecords(studentId: string): Promise<Array<ExamRecord>>;
    getUserProfile(userId: Principal): Promise<UserProfile | null>;
    importData(data: string): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    logSMS(log: SMSLog): Promise<void>;
    resetUserPassword(userId: Principal): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    transferStudent(id: string): Promise<void>;
    updateExamRecord(record: ExamRecord): Promise<void>;
    updateFinancialRecord(record: FinancialRecord): Promise<void>;
    updateStaff(staff: Staff): Promise<void>;
    updateStudent(student: Student): Promise<void>;
    updateUser(userId: Principal, updatedProfile: UserProfile): Promise<void>;
}
import type { AdmissionStatus as _AdmissionStatus, AppRole as _AppRole, ExamRecord as _ExamRecord, ExternalBlob as _ExternalBlob, FinancialRecord as _FinancialRecord, FinancialType as _FinancialType, Staff as _Staff, StaffStatus as _StaffStatus, Student as _Student, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addExamRecord(arg0: ExamRecord): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addExamRecord(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addExamRecord(arg0);
            return result;
        }
    }
    async addFinancialRecord(arg0: FinancialRecord): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addFinancialRecord(to_candid_FinancialRecord_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFinancialRecord(to_candid_FinancialRecord_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n12(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n12(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createStaff(arg0: Staff): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createStaff(await to_candid_Staff_n14(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createStaff(await to_candid_Staff_n14(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createStudent(arg0: Student): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createStudent(await to_candid_Student_n19(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createStudent(await to_candid_Student_n19(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createUser(arg0: Principal, arg1: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createUser(arg0, await to_candid_UserProfile_n23(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createUser(arg0, await to_candid_UserProfile_n23(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteExamRecord(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteExamRecord(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteExamRecord(arg0);
            return result;
        }
    }
    async deleteFinancialRecord(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFinancialRecord(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFinancialRecord(arg0);
            return result;
        }
    }
    async deleteStaff(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteStaff(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteStaff(arg0);
            return result;
        }
    }
    async deleteStudent(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteStudent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteStudent(arg0);
            return result;
        }
    }
    async disableUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.disableUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.disableUser(arg0);
            return result;
        }
    }
    async dismissStudent(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.dismissStudent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.dismissStudent(arg0);
            return result;
        }
    }
    async exportAllData(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.exportAllData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.exportAllData();
            return result;
        }
    }
    async getAllExamRecords(): Promise<Array<ExamRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllExamRecords();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllExamRecords();
            return result;
        }
    }
    async getAllFinancialRecords(): Promise<Array<FinancialRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllFinancialRecords();
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllFinancialRecords();
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllStaff(): Promise<Array<Staff>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllStaff();
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllStaff();
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllStudents(): Promise<Array<Student>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllStudents();
                return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllStudents();
            return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllUsers(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsers();
                return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsers();
            return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAuditLogs(): Promise<Array<AuditLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAuditLogs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAuditLogs();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async getExamRecord(arg0: string): Promise<ExamRecord | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getExamRecord(arg0);
                return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExamRecord(arg0);
            return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFinancialRecord(arg0: string): Promise<FinancialRecord | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getFinancialRecord(arg0);
                return from_candid_opt_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFinancialRecord(arg0);
            return from_candid_opt_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSMSLogs(): Promise<Array<SMSLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSMSLogs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSMSLogs();
            return result;
        }
    }
    async getStaff(arg0: string): Promise<Staff | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStaff(arg0);
                return from_candid_opt_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStaff(arg0);
            return from_candid_opt_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudent(arg0: string): Promise<Student | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudent(arg0);
                return from_candid_opt_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudent(arg0);
            return from_candid_opt_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudentExamRecords(arg0: string): Promise<Array<ExamRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudentExamRecords(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudentExamRecords(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async importData(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.importData(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.importData(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async logSMS(arg0: SMSLog): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logSMS(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logSMS(arg0);
            return result;
        }
    }
    async resetUserPassword(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resetUserPassword(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetUserPassword(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n23(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n23(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async transferStudent(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.transferStudent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transferStudent(arg0);
            return result;
        }
    }
    async updateExamRecord(arg0: ExamRecord): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateExamRecord(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateExamRecord(arg0);
            return result;
        }
    }
    async updateFinancialRecord(arg0: FinancialRecord): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFinancialRecord(to_candid_FinancialRecord_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFinancialRecord(to_candid_FinancialRecord_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateStaff(arg0: Staff): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStaff(await to_candid_Staff_n14(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStaff(await to_candid_Staff_n14(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateStudent(arg0: Student): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStudent(await to_candid_Student_n19(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStudent(await to_candid_Student_n19(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateUser(arg0: Principal, arg1: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUser(arg0, await to_candid_UserProfile_n23(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUser(arg0, await to_candid_UserProfile_n23(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_AdmissionStatus_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AdmissionStatus): AdmissionStatus {
    return from_candid_variant_n43(_uploadFile, _downloadFile, value);
}
function from_candid_AppRole_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AppRole): AppRole {
    return from_candid_variant_n48(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_FinancialRecord_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FinancialRecord): FinancialRecord {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_FinancialType_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FinancialType): FinancialType {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid_StaffStatus_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StaffStatus): StaffStatus {
    return from_candid_variant_n36(_uploadFile, _downloadFile, value);
}
async function from_candid_Staff_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Staff): Promise<Staff> {
    return await from_candid_record_n34(_uploadFile, _downloadFile, value);
}
async function from_candid_Student_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Student): Promise<Student> {
    return await from_candid_record_n41(_uploadFile, _downloadFile, value);
}
async function from_candid_UserProfile_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): Promise<UserProfile> {
    return await from_candid_record_n46(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n50(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n38(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): Promise<UserProfile | null> {
    return value.length === 0 ? null : await from_candid_UserProfile_n45(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExamRecord]): ExamRecord | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FinancialRecord]): FinancialRecord | null {
    return value.length === 0 ? null : from_candid_FinancialRecord_n28(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Staff]): Promise<Staff | null> {
    return value.length === 0 ? null : await from_candid_Staff_n33(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Student]): Promise<Student | null> {
    return value.length === 0 ? null : await from_candid_Student_n40(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    description: string;
    recordType: _FinancialType;
    systemId: string;
    timestamp: bigint;
    amount: number;
}): {
    description: string;
    recordType: FinancialType;
    systemId: string;
    timestamp: bigint;
    amount: number;
} {
    return {
        description: value.description,
        recordType: from_candid_FinancialType_n30(_uploadFile, _downloadFile, value.recordType),
        systemId: value.systemId,
        timestamp: value.timestamp,
        amount: value.amount
    };
}
async function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _StaffStatus;
    name: string;
    systemId: string;
    photo: [] | [_ExternalBlob];
    position: string;
}): Promise<{
    status: StaffStatus;
    name: string;
    systemId: string;
    photo?: ExternalBlob;
    position: string;
}> {
    return {
        status: from_candid_StaffStatus_n35(_uploadFile, _downloadFile, value.status),
        name: value.name,
        systemId: value.systemId,
        photo: record_opt_to_undefined(await from_candid_opt_n37(_uploadFile, _downloadFile, value.photo)),
        position: value.position
    };
}
async function from_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _AdmissionStatus;
    parentPhone: string;
    systemId: string;
    photo: [] | [_ExternalBlob];
    className: string;
    lastName: string;
    parentName: string;
    firstName: string;
}): Promise<{
    status: AdmissionStatus;
    parentPhone: string;
    systemId: string;
    photo?: ExternalBlob;
    className: string;
    lastName: string;
    parentName: string;
    firstName: string;
}> {
    return {
        status: from_candid_AdmissionStatus_n42(_uploadFile, _downloadFile, value.status),
        parentPhone: value.parentPhone,
        systemId: value.systemId,
        photo: record_opt_to_undefined(await from_candid_opt_n37(_uploadFile, _downloadFile, value.photo)),
        className: value.className,
        lastName: value.lastName,
        parentName: value.parentName,
        firstName: value.firstName
    };
}
async function from_candid_record_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: boolean;
    appRole: _AppRole;
    role: _UserRole;
    lastUpdated: bigint;
    fullName: string;
    systemId: string;
    photo: [] | [_ExternalBlob];
}): Promise<{
    active: boolean;
    appRole: AppRole;
    role: UserRole;
    lastUpdated: bigint;
    fullName: string;
    systemId: string;
    photo?: ExternalBlob;
}> {
    return {
        active: value.active,
        appRole: from_candid_AppRole_n47(_uploadFile, _downloadFile, value.appRole),
        role: from_candid_UserRole_n49(_uploadFile, _downloadFile, value.role),
        lastUpdated: value.lastUpdated,
        fullName: value.fullName,
        systemId: value.systemId,
        photo: record_opt_to_undefined(await from_candid_opt_n37(_uploadFile, _downloadFile, value.photo))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    revenue: null;
} | {
    expense: null;
}): FinancialType {
    return "revenue" in value ? FinancialType.revenue : "expense" in value ? FinancialType.expense : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    transferred: null;
} | {
    dismissed: null;
}): StaffStatus {
    return "active" in value ? StaffStatus.active : "transferred" in value ? StaffStatus.transferred : "dismissed" in value ? StaffStatus.dismissed : value;
}
function from_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    transferred: null;
} | {
    dismissed: null;
} | {
    promoted: null;
}): AdmissionStatus {
    return "active" in value ? AdmissionStatus.active : "transferred" in value ? AdmissionStatus.transferred : "dismissed" in value ? AdmissionStatus.dismissed : "promoted" in value ? AdmissionStatus.promoted : value;
}
function from_candid_variant_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    accountant: null;
} | {
    examsCoordinator: null;
} | {
    headmaster: null;
}): AppRole {
    return "accountant" in value ? AppRole.accountant : "examsCoordinator" in value ? AppRole.examsCoordinator : "headmaster" in value ? AppRole.headmaster : value;
}
function from_candid_variant_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FinancialRecord>): Array<FinancialRecord> {
    return value.map((x)=>from_candid_FinancialRecord_n28(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Staff>): Promise<Array<Staff>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Staff_n33(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Student>): Promise<Array<Student>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Student_n40(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserProfile>): Promise<Array<UserProfile>> {
    return await Promise.all(value.map(async (x)=>await from_candid_UserProfile_n45(_uploadFile, _downloadFile, x)));
}
function to_candid_AdmissionStatus_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AdmissionStatus): _AdmissionStatus {
    return to_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function to_candid_AppRole_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppRole): _AppRole {
    return to_candid_variant_n26(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_FinancialRecord_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FinancialRecord): _FinancialRecord {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_FinancialType_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FinancialType): _FinancialType {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_StaffStatus_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StaffStatus): _StaffStatus {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
async function to_candid_Staff_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Staff): Promise<_Staff> {
    return await to_candid_record_n15(_uploadFile, _downloadFile, value);
}
async function to_candid_Student_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Student): Promise<_Student> {
    return await to_candid_record_n20(_uploadFile, _downloadFile, value);
}
async function to_candid_UserProfile_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): Promise<_UserProfile> {
    return await to_candid_record_n24(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: StaffStatus;
    name: string;
    systemId: string;
    photo?: ExternalBlob;
    position: string;
}): Promise<{
    status: _StaffStatus;
    name: string;
    systemId: string;
    photo: [] | [_ExternalBlob];
    position: string;
}> {
    return {
        status: to_candid_StaffStatus_n16(_uploadFile, _downloadFile, value.status),
        name: value.name,
        systemId: value.systemId,
        photo: value.photo ? candid_some(await to_candid_ExternalBlob_n18(_uploadFile, _downloadFile, value.photo)) : candid_none(),
        position: value.position
    };
}
async function to_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: AdmissionStatus;
    parentPhone: string;
    systemId: string;
    photo?: ExternalBlob;
    className: string;
    lastName: string;
    parentName: string;
    firstName: string;
}): Promise<{
    status: _AdmissionStatus;
    parentPhone: string;
    systemId: string;
    photo: [] | [_ExternalBlob];
    className: string;
    lastName: string;
    parentName: string;
    firstName: string;
}> {
    return {
        status: to_candid_AdmissionStatus_n21(_uploadFile, _downloadFile, value.status),
        parentPhone: value.parentPhone,
        systemId: value.systemId,
        photo: value.photo ? candid_some(await to_candid_ExternalBlob_n18(_uploadFile, _downloadFile, value.photo)) : candid_none(),
        className: value.className,
        lastName: value.lastName,
        parentName: value.parentName,
        firstName: value.firstName
    };
}
async function to_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: boolean;
    appRole: AppRole;
    role: UserRole;
    lastUpdated: bigint;
    fullName: string;
    systemId: string;
    photo?: ExternalBlob;
}): Promise<{
    active: boolean;
    appRole: _AppRole;
    role: _UserRole;
    lastUpdated: bigint;
    fullName: string;
    systemId: string;
    photo: [] | [_ExternalBlob];
}> {
    return {
        active: value.active,
        appRole: to_candid_AppRole_n25(_uploadFile, _downloadFile, value.appRole),
        role: to_candid_UserRole_n12(_uploadFile, _downloadFile, value.role),
        lastUpdated: value.lastUpdated,
        fullName: value.fullName,
        systemId: value.systemId,
        photo: value.photo ? candid_some(await to_candid_ExternalBlob_n18(_uploadFile, _downloadFile, value.photo)) : candid_none()
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    description: string;
    recordType: FinancialType;
    systemId: string;
    timestamp: bigint;
    amount: number;
}): {
    description: string;
    recordType: _FinancialType;
    systemId: string;
    timestamp: bigint;
    amount: number;
} {
    return {
        description: value.description,
        recordType: to_candid_FinancialType_n10(_uploadFile, _downloadFile, value.recordType),
        systemId: value.systemId,
        timestamp: value.timestamp,
        amount: value.amount
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FinancialType): {
    revenue: null;
} | {
    expense: null;
} {
    return value == FinancialType.revenue ? {
        revenue: null
    } : value == FinancialType.expense ? {
        expense: null
    } : value;
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StaffStatus): {
    active: null;
} | {
    transferred: null;
} | {
    dismissed: null;
} {
    return value == StaffStatus.active ? {
        active: null
    } : value == StaffStatus.transferred ? {
        transferred: null
    } : value == StaffStatus.dismissed ? {
        dismissed: null
    } : value;
}
function to_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AdmissionStatus): {
    active: null;
} | {
    transferred: null;
} | {
    dismissed: null;
} | {
    promoted: null;
} {
    return value == AdmissionStatus.active ? {
        active: null
    } : value == AdmissionStatus.transferred ? {
        transferred: null
    } : value == AdmissionStatus.dismissed ? {
        dismissed: null
    } : value == AdmissionStatus.promoted ? {
        promoted: null
    } : value;
}
function to_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppRole): {
    accountant: null;
} | {
    examsCoordinator: null;
} | {
    headmaster: null;
} {
    return value == AppRole.accountant ? {
        accountant: null
    } : value == AppRole.examsCoordinator ? {
        examsCoordinator: null
    } : value == AppRole.headmaster ? {
        headmaster: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
